###
GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:3000/contacts HTTP/1.1

###
GET http://localhost:3000/:id HTTP/1.1

# ###
# GET http://localhost:3000/luffy HTTP/1.1

# ###
# GET http://localhost:3000/data HTTP/1.1

###
GET https://cse-341-test-zcym.onrender.com/contacts HTTP/1.1