###
GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:8080/contacts HTTP/1.1

###
GET http://localhost:8080/api-docs HTTP/1.1


###
GET http://localhost:3000/contacts/650d9089580a3e6050fc46b4 HTTP/1.1

###
GET http://localhost:3000/contacts/650da22e580a3e6050fc46b7 HTTP/1.1

###
GET http://localhost:3000/contacts/650da17c580a3e6050fc46b6 HTTP/1.1

###
GET https://cse-341-test-zcym.onrender.com/contacts HTTP/1.1

###
GET https://cse-341-test-zcym.onrender.com/contacts/650da17c580a3e6050fc46b6 HTTP/1.1

###
GET https://cse-341-test-zcym.onrender.com/contacts/650da22e580a3e6050fc46b7 HTTP/1.1

###
GET https://cse-341-test-zcym.onrender.com/contacts/ HTTP/1.1

### Update 
PUT https://cse-341-test-zcym.onrender.com/contacts/65186d14934c5ce8c473e810 HTTP/1.1
content-type: application/json

{
"firstName":"Sanji", 
"lastName":"Black Legs", 
"email":"test@gmail.com", 
"favoriteColor":"All blue", 
"birthday":"IDK"
}

### add
POST https://cse-341-test-zcym.onrender.com/contacts HTTP/1.1
content-type: application/json

{
"firstName":"Luffy", 
"lastName":"Monkey D.", 
"email":"aWeaver@test.com", 
"favoriteColor":"Red", 
"birthday":"IDK"
}

###
DELETE https://cse-341-test-zcym.onrender.com/contacts/65186d14934c5ce8c473e810 HTTP/1.1

###
GET https://cse-341-test-zcym.onrender.com/api-docs HTTP/1.1

# ###
# GET http://localhost:3000/luffy HTTP/1.1

# ###
# GET http://localhost:3000/data HTTP/1.1

